name: Test Report

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Test report
        uses: dorny/test-reporter@v1
        with:
          name: Test results
          path: junit.xml
          reporter: jest-junit

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
